# Задержка после загрузки вкладки перед скриншотом (def. 1000)
ss_delay = 1000

# Небольшая пауза (мс) перед подтверждением скриншота, после того как окно
# выделения точно открылось (def. 100)
enter_delay = 100

# Сколько максимум ждать (мс), пока откроется окно выделения скриншота,
# прежде чем отменить попытку (def. 5000)
enter_max_wait = 5000

# Задержка перед отправкой скриншотов после окончания работы auto (def. 500)

tg_delay = 500