# Задержка после загрузки вкладки перед скриншотом (def. 300)
ss_delay = 300

# Задержка между комбинациями в Lightshot (def. 300)
lightshot_delay = 300

# Задержка перед отправкой скриншотов после окончания работы auto (def. 0)

tg_delay = 0